# Generated by Django 2.2 on 2021-11-17 10:09

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_user', models.CharField(blank=True, default='admin', max_length=64, null=True, verbose_name='修改人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('identifies', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='分组标识')),
                ('name', models.CharField(max_length=128, verbose_name='分组名称')),
            ],
            options={
                'verbose_name': '模型分组',
                'verbose_name_plural': '模型分组',
                'db_table': 'cmdb_model_group',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_user', models.CharField(blank=True, default='admin', max_length=64, null=True, verbose_name='修改人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('identifies', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='模型标识')),
                ('name', models.CharField(max_length=128, verbose_name='模型名称')),
                ('icon', models.CharField(max_length=128, verbose_name='模型图标')),
                ('is_usable', models.BooleanField(default=True, verbose_name='是否可用')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Group', verbose_name='模型分组')),
            ],
            options={
                'verbose_name': '模型',
                'verbose_name_plural': '模型',
                'db_table': 'cmdb_model_info',
                'ordering': ['id'],
                'unique_together': {('identifies', 'group')},
            },
        ),
        migrations.CreateModel(
            name='InfoRelatedType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_user', models.CharField(blank=True, default='admin', max_length=64, null=True, verbose_name='修改人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('identifies', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='关系标识')),
                ('name', models.CharField(max_length=128, verbose_name='关系名称')),
                ('source_desc', models.CharField(max_length=200, verbose_name='源-目标描述')),
                ('target_desc', models.CharField(max_length=200, verbose_name='目标-源描述')),
                ('direction', models.PositiveSmallIntegerField(choices=[(1, '有方向'), (2, '双向'), (3, '无方向')], verbose_name='方向')),
            ],
            options={
                'verbose_name': '模型关系类型',
                'verbose_name_plural': '模型关系类型',
                'db_table': 'cmdb_model_related_type',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FieldGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_user', models.CharField(blank=True, default='admin', max_length=64, null=True, verbose_name='修改人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='分组名称')),
                ('sequence', models.PositiveSmallIntegerField(default=999, verbose_name='分组显示顺序')),
                ('is_fold', models.BooleanField(default=False, verbose_name='是否折叠')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Info', verbose_name='模型')),
            ],
            options={
                'verbose_name': '字段分组',
                'verbose_name_plural': '字段分组',
                'db_table': 'cmdb_model_field_group',
                'ordering': ['id', 'sequence'],
                'unique_together': {('name', 'info')},
            },
        ),
        migrations.CreateModel(
            name='InfoRelated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_user', models.CharField(blank=True, default='admin', max_length=64, null=True, verbose_name='修改人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('constraint', models.PositiveSmallIntegerField(choices=[(1, '1-1'), (2, '1-N'), (3, 'N-N')], verbose_name='源到目的约束')),
                ('remark', models.CharField(blank=True, default='0', max_length=200, verbose_name='关联描述')),
                ('related_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.InfoRelatedType', verbose_name='关系类型')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_source', to='cmdb.Info', verbose_name='源模型')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_target', to='cmdb.Info', verbose_name='目标模型')),
            ],
            options={
                'verbose_name': '模型关系',
                'verbose_name_plural': '模型关系',
                'db_table': 'cmdb_model_info_related',
                'ordering': ['id'],
                'unique_together': {('source', 'target', 'related_type', 'constraint')},
            },
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_user', models.CharField(blank=True, default='admin', max_length=64, null=True, verbose_name='修改人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('identifies', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='字段标识')),
                ('name', models.CharField(max_length=128, verbose_name='字段名称')),
                ('type', models.CharField(choices=[('string', '字符'), ('text', '文本'), ('number', '数字'), ('list', '列表'), ('enum', '枚举'), ('date', '日期'), ('time', '时间'), ('bool', '布尔')], max_length=10, verbose_name='字段类型')),
                ('is_edit', models.BooleanField(default=True, verbose_name='是否可编辑')),
                ('is_unique', models.BooleanField(default=False, verbose_name='是否唯一')),
                ('required', models.BooleanField(default=True, verbose_name='是否必须填写')),
                ('prompt', models.CharField(max_length=200, verbose_name='用户提示')),
                ('configuration', jsonfield.fields.JSONField(verbose_name='字段配置项')),
                ('is_list_display', models.BooleanField(default=False, verbose_name='是否列表显示')),
                ('list_display_sort', models.PositiveSmallIntegerField(default=999, verbose_name='列表显示顺序')),
                ('field_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.FieldGroup', verbose_name='字段分组')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Info', verbose_name='模型')),
            ],
            options={
                'verbose_name': '字段',
                'verbose_name_plural': '字段',
                'db_table': 'cmdb_model_fields',
                'ordering': ['id'],
                'unique_together': {('identifies', 'info'), ('name', 'info')},
            },
        ),
    ]
