# Generated by Django 2.2 on 2021-11-18 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_data_datarelated_datatagrelated_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarelated',
            name='source_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_info', to='cmdb.Info', verbose_name='源模型'),
        ),
        migrations.AlterField(
            model_name='fields',
            name='prompt',
            field=models.CharField(blank=True, default='unknow', max_length=200, null=True, verbose_name='用户提示'),
        ),
        migrations.AlterField(
            model_name='fields',
            name='required',
            field=models.BooleanField(default=False, verbose_name='是否必须填写'),
        ),
        migrations.AlterField(
            model_name='fields',
            name='type',
            field=models.CharField(choices=[('string', '字符'), ('text', '文本'), ('number', '数字'), ('list', '列表'), ('enum', '枚举'), ('date', '日期'), ('time', '时间'), ('bool', '布尔'), ('user', '用户')], max_length=10, verbose_name='字段类型'),
        ),
        migrations.AlterField(
            model_name='info',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='cmdb.Group', verbose_name='模型分组'),
        ),
    ]
