# Generated by Django 2.2 on 2021-11-18 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20211118_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldgroup',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='cmdb.Info', verbose_name='模型'),
        ),
        migrations.AlterField(
            model_name='fields',
            name='field_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_groups', to='cmdb.FieldGroup', verbose_name='字段分组'),
        ),
    ]
