# Generated by Django 2.2.16 on 2022-02-16 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('host', '0004_host_environments'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmdTemplateCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='类别名称')),
            ],
        ),
        migrations.CreateModel(
            name='CmdTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(blank=True, max_length=32, null=True)),
                ('cmd', models.TextField(verbose_name='模板内容')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述信息')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtask.CmdTemplateCategory', verbose_name='模板类别')),
            ],
        ),
        migrations.CreateModel(
            name='CmdExexHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exec_time', models.DateTimeField(auto_now_add=True, verbose_name='指令执行时间')),
                ('hosts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='host.Host')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mtask.CmdTemplate')),
            ],
        ),
    ]
