# Generated by Django 2.2.16 on 2022-02-16 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='环境名称')),
                ('tag', models.CharField(max_length=32, verbose_name='标识符')),
                ('desc', models.CharField(blank=True, max_length=32, null=True, verbose_name='描述信息')),
            ],
        ),
    ]
