# Generated by Django 2.2.16 on 2022-02-20 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('host', '0004_host_environments'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_beat', models.IntegerField(blank=True, help_text='方便我们通过这个id值来控制celery的任务状态', null=True, verbose_name='django-celery-beat任务id')),
                ('task_name', models.CharField(max_length=32, verbose_name='任务名称')),
                ('task_cmd', models.TextField(verbose_name='任务指令')),
                ('period_way', models.CharField(choices=[('1', '普通周期'), ('2', '一次性任务'), ('3', 'cron任务')], default='1', max_length=32, verbose_name='任务周期方式')),
                ('period_content', models.CharField(max_length=32, verbose_name='周期计划')),
                ('period_status', models.CharField(choices=[('1', '激活'), ('2', '停止'), ('3', '报错')], default='1', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TaskHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.Host', verbose_name='任务执行主机')),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.TaskSchedule', verbose_name='执行的任务')),
            ],
        ),
    ]
