# Generated by Django 2.2.16 on 2022-02-16 03:54

from django.db import migrations, models
import django.db.models.deletion
import utils.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('orders', models.IntegerField(default=1, verbose_name='排序')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=32)),
                ('app_id', models.CharField(default=utils.functions.GenerateShortId, editable=False, max_length=32, unique=True, verbose_name='应用唯一标识号')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注信息')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.UserProfile', verbose_name='用户')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
