# Generated by Django 2.2.16 on 2022-02-16 21:03

import Stargate.utils.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newrelease', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseapp',
            name='app_id',
            field=models.CharField(default=Stargate.utils.functions.GenerateShortId, editable=False, max_length=32, verbose_name='应用唯一标识号'),
        ),
    ]
