# Generated by Django 2.2.16 on 2022-02-19 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newrelease', '0005_releaseapply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaserecord',
            name='release_app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='release_application', to='newrelease.ReleaseApp', verbose_name='发布从属应用'),
        ),
    ]
