# Generated by Django 2.2.16 on 2022-02-16 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confcenter', '0001_initial'),
        ('host', '0003_auto_20220210_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='environments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='confcenter.Environment', verbose_name='从属环境'),
        ),
    ]
