# Generated by Django 2.2.16 on 2022-01-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy',
            name='info',
            field=models.CharField(max_length=100, null=True, verbose_name='版本描述'),
        ),
    ]
