# Generated by Django 2.2 on 2021-12-07 17:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_user', models.CharField(blank=True, default='admin', max_length=64, null=True, verbose_name='修改人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('appid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='应用ID')),
                ('appname', models.CharField(max_length=64, unique=True, verbose_name='应用名称')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='应用描述')),
            ],
            options={
                'verbose_name': '应用id',
                'verbose_name_plural': '应用id',
                'ordering': ['appid'],
            },
        ),
        migrations.CreateModel(
            name='WxMsgLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_date', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('msg_type', models.CharField(max_length=64, verbose_name='消息类型')),
                ('msg', models.TextField(max_length=40960, verbose_name='消息内容')),
                ('status', models.CharField(choices=[('success', '发送成功'), ('failed', '发送失败')], default='success', max_length=16, verbose_name='发送状态')),
                ('detail', models.TextField(verbose_name='详情')),
                ('appid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='msg.AppID', verbose_name='应用ID')),
            ],
            options={
                'verbose_name': '微信消息',
                'verbose_name_plural': '微信消息',
                'ordering': ['msg_date'],
            },
        ),
    ]
