# Generated by Django 2.2.16 on 2022-01-10 03:31

import Stargate.utils.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appid',
            options={'ordering': ['create_time'], 'verbose_name': '应用id', 'verbose_name_plural': '应用id'},
        ),
        migrations.AlterModelOptions(
            name='wxmsglogs',
            options={'ordering': ['-msg_date'], 'verbose_name': '微信消息日志', 'verbose_name_plural': '微信消息日志'},
        ),
        migrations.AlterField(
            model_name='appid',
            name='appid',
            field=models.CharField(default=Stargate.utils.functions.GenerateShortId, editable=False, max_length=32, verbose_name='应用ID'),
        ),
    ]
